### ISSUE TITLE
win11不适配

### ISSUE THREAD

**Issue by 775589898** [itihey/tikuAdapter#12]
win11运行exe时提示“此应用无法在你的电脑上运行若要找到适用于你的电脑的版本，请咨询软件发布者”。在属性上设置兼容性运行，但是选项为空，希望能够适配一下win11

**Comment by DokiDoki1103** [comment]
可以贴一下截图吗？

**Comment by DokiDoki1103** [comment]
<img width="1278" alt="图片" src="https://github.com/itihey/tikuAdapter/assets/62740231/23bfd8a2-6051-433a-8907-7c6170b8cb2b">
一般情况下 win11应该是amd架构的，您这两个版本都测试过都不行吗？

方便查询您的电脑的操作系统架构吗？

**Comment by DokiDoki1103** [comment]
您的操作系统是32位还是64位呢？

**Comment by 775589898** [comment]
> 您的操作系统是32位还是64位呢？

64位
![微信截图_20231103180252](https://github.com/itihey/tikuAdapter/assets/77394274/8bc94b55-6ad3-4f39-a0ad-74b322327222)

**Comment by DokiDoki1103** [comment]
您下载 amd64的也不行吗？

**Comment by DokiDoki1103** [comment]
> > 您的操作系统是32位还是64位呢？
> 
> 64位 ![微信截图_20231103180252](https://user-images.githubusercontent.com/77394274/280241812-8bc94b55-6ad3-4f39-a0ad-74b322327222.png)

现在解决了吗？

**Comment by 775589898** [comment]
> 注意是amd64而不是arm64

好了，发现是我下错了版本！非常感谢！

**Comment by 775589898** [comment]
> > > 您的操作系统是32位还是64位呢？
> > 
> > 
> > 64位 ![微信截图_20231103180252](https://user-images.githubusercontent.com/77394274/280241812-8bc94b55-6ad3-4f39-a0ad-74b322327222.png)
> 
> 现在解决了吗？

解决了！！！！非常感谢！！！！！！！！！！！！！！！！！！！爱你哟
