### ISSUE TITLE
接入 爱点题库

### ISSUE THREAD

**Issue by DokiDoki1103** [itihey/tikuAdapter#4]
接入 爱点题库

**Comment by aidiantiku** [comment]
爱点题库网址 [www.51aidian.com](https://www.51aidian.com)  以下各类题库API接口Token均可在爱点官网申请授权

接口一：私有题库API
说明：可在爱点题库后台上传私有试题资源，并通过此接口调用试题题库
url：http://new.api.51aidian.com/privates/Mytiku
Content-Type: application/json
请求体：
{
    "token": "接口Token", 
    "question": "题目" 
}
响应体：
{
    "code": 1, 
    "msg": "请求成功", 
    "private_tiku": [
        {
            "question": "任何线性规划问题存在唯一的对偶问题。\n", 
            "options": [],
            "answer": "正确" 
             }
    ] 
   }
接口文档地址：https://docs.apipost.cn/preview/ec9de861e91aa049/aeba0e473ab3a170?target_id=e86c51cb-c7e0-4fcb-985c-8c1dc64c32dc  

接口二：亿级题库-免费版
说明：可在爱点题库后台上传私有试题资源，并通过此接口调用试题题库
url：http://new.api.51aidian.com/publics/newapi/freedirect
Content-Type: application/json
请求体：
{
    "token": "接口Token", 
    "question": "题目" 
}
响应体：
{
	"code": 1,
	"msg": "获取成功",
	"qlist": [
		{
			"qid": "kdCCLeLmJllnAFxiPTCZylkQG08NkEEKnvaU5ReW3DFfZ%2B7wXBJ8hfkZfB2o60F9492FwATMujRrre7ygmFQOqAv%2F18pMPqEVPvP8IW9xOSr0744KfOVtRg45CbPdYMRoXlDzhkMui%2BzKEouuJOIvw%3D%3D",
			"question": "战略与战略推演是一种包含关系。",
			"options": [],
			"answer": [
				"正确"
			]
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZyqB4YRFtJLkIZS6TXQGxRpPVaaRQKIw7ajqH%2Bi7i%2B2QRcNC3QA2ubehsz%2FMR8oj3nMBQRbzRYuEDyDCX6SvQESh7rpEGRh7ucceGTqWwTNuFjSZdJRuElrNAdNgD7YW15A%3D%3D",
			"question": "（     ）是企业发展的战略支撑，是在市场竞争中实现企业价值、赢得未来的制胜之道。",
			"options": [],
			"answer": [
				"创新"
			]
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZyiNpfAq6YyLklLSO6N5K4b0Y5sRj20%2F%2Bmer8IC%2BqVibnT8l%2BkdMmvVyO0Jc487VaVJ2HKuPVCTTofoSGgZvJfxuHZ7otoWR13BEGRWPvtArNk0UhlVcV5mVfnPli5taRdg%3D%3D",
			"question": "战略推演就是战略规划。（　）",
			"options": [],
			"answer": [
				"错误"
			]
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZytM6bsleO7QdlIWOeptkdxmgcHOoLy%2Br4tJdw0L6zHY7WDKYN1%2FQ8DMDxHwJrUqgPSsvKJY8PA8U7bZGLo8uNJIGNQvec9rDiyPLokn56CSdwRYWbht4qe9LLlK%2FfUu4ew%3D%3D",
			"question": "战略推演就是战略规划。（)",
			"options": [
				"是",
				"否"
			],
			"answer": [
				"否"
			]
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZysza59NPxMmcUDeU1AvLLisQ5faZpavqLgC1PNSvIpLZfhV0%2BE58bayUaAOaizc186xSdr%2F7E1J2Hr3owmvxM8L3bnuRFqn4vLXgXyRz64j%2FvuhXS3WO6pWOfKhCjS9YgQ%3D%3D",
			"question": "与竞争战略相比，商业模式更关注的是商业生态系统。",
			"options": [],
			"answer": [
				"对"
			]
		}
	]
}
接口文档地址：https://docs.apipost.cn/preview/27844aedd6bd8b77/d0c719f0025a5bf2?target_id=210c40d6-956a-44f4-9150-817f0c12c9aa


接口三：促销题库-免费版
说明：可在爱点题库后台上传私有试题资源，并通过此接口调用试题题库
url：http://new.api.51aidian.com/publics/newapi/freeoldapi
Content-Type: application/json
请求体：
{
    "token": "接口Token", 
    "question": "题目" 
}
响应体：
{
	"code": 1,
	"msg": "获取成功",
	"qlist": [
		{
			"qid": "kdCCLeLmJllnAFxiPTCZyrPNwEI58UF%2B%2BEQwB5h98h9x%2B9a7Kg7IUPcGvd5Av7841AL%2FFnOnOinlt1B75ipWvR8ZD8HCwWBriuK1RHdBMEnOiEH4Am3uouVDNyjWWelHN%2BolqC21xngIh8FHA5zEAQ%3D%3D",
			"question": "21世纪海上丝绸之路的两大走向是指( )。A.从中国沿海港口过南海，经马六甲海峡到印度洋，延伸至21世纪海上丝绸之路的两大走向是指( )。A.从中国沿海港口过南海，经马六甲海峡到印度洋，延伸至欧洲B.从中国沿海港口过南海，向南太平洋延伸",
			"options": "",
			"answer": "AB"
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZymcDHbT4lZKy762XnvzvxCbA9goj18AlbIwg1JnLFksy5OBQK19VFFRqLUnV%2FFnEa%2FxAyqecA9FHC5uVWLFQLiFWm6KYKLa%2FuQNuPQLHB3PubSiXTVNpAjJg4WZM7w3ViA%3D%3D",
			"question": "21世纪海上丝绸之路有两大走向，一是从中国沿海港口过南海，经马六甲海峡到印度洋，延伸至欧洲；二是从中国沿海港口过南海，向南太平洋延伸",
			"options": "",
			"answer": "对 "
		},
		{
			"qid": "kdCCLeLmJllnAFxiPTCZyitBgL1%2BiDwMHVfwpgtbccEjavFhLEFFsKwfp2jaNK8YEIi6CDYL%2F52PM%2BfWuTACQGI6dQH38fJ5J4wV6uVcuYmq6K5rQoqygFeBGlDlp0h4fTNkAbxfO7ndbNjngmE8Wg%3D%3D",
			"question": "21世纪海上丝绸之路有两大走向，一是从中国沿海港口过南海，经马六甲海峡到印度洋，延伸至欧洲；二是从中国沿海港口过南海，向南太平洋延伸",
			"options": "",
			"answer": "√"
		}
	]
}
接口文档地址：https://docs.apipost.cn/preview/1806e43f4b06aaf4/4d0b1822b8e3b1d8?target_id=1f64995a-6220-45b6-9332-5f5a280f78d1

接口四：亿级题库-付费版
说明：接口格式与免费版一致
url：http://new.api.51aidian.com/publics/newapi/direct
接口文档地址：https://docs.apipost.cn/preview/1e8289ae293595b1/72ccbe52e2f2b62f?target_id=80bf0b95-89e0-4f18-aa3e-beb7ab1c2346

接口五：促销题库-付费版
说明：接口格式与免费版一致
url：http://new.api.51aidian.com/publics/newapi/oldapi
接口文档地址：https://docs.apipost.cn/preview/eda0a9fc7b4e9726/2a697f8b8b3e3e81?target_id=cd981c4f-8dcf-45c5-9fab-83441ad5c89b

**Comment by DokiDoki1103** [comment]
https://github.com/itihey/tikuAdapter/commit/d00ee6d9ad0a3ace2524e0a794f8348a81eb4c24
